version: 0.0
os: linux

files:
  - source: /
    destination: /devlogClient
    overwrite: yes

permissions:
  - object: /devlogClient
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
