import Header from '../components/Header';
import '../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </head>
      <body>
        <Header />
        <main className="max-w-7xl m-auto relative max-h-screen flex flex-col items-center h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
